import type { Language } from '@/types';

export const aiUiCopy = {
    en: {
        quizFeedbackTitle: 'AI memory coach',
        quizFeedbackLoading: 'Preparing a memorable explanation...',
        quizFeedbackGuestLimit: 'Guest preview used. Sign in to unlock full AI mistake feedback.',
        quizFeedbackContinue: 'Continue',
        quizFeedbackCta: 'Open Profile',
        whyWrong: 'Why this missed',
        whyCorrect: 'What to remember',
        memoryHook: 'Memory hook',
        confusedWith: 'Often confused with',
        explainLabel: 'AI explain',
        explainLoading: 'Preparing AI explanation...',
        explainGuestLimit: 'Guest preview used. Sign in to unlock full AI explanations.',
        explainModes: {
            simple: 'Simplify it',
            example: 'Explain with example',
            'language-bridge': 'Bridge TR / EN / RU',
            importance: 'Why it matters',
        },
        studyCoachTitle: 'AI Study Coach',
        studyCoachDescription: 'Build today’s plan from your weak spots, favorites, and review load.',
        studyCoachGuest: 'AI Study Coach is reserved for full members.',
        studyCoachCompleteProfile: 'Complete your profile to unlock AI Study Coach.',
        studyCoachAction: 'Build today’s plan',
        studyCoachLoading: 'Building your AI study plan...',
        studyCoachFocusAreas: 'Focus Areas',
        studyCoachPlan: 'Today’s Plan',
        studyCoachReason: 'Why this plan',
        studyCoachNote: 'Coach note',
        genericError: 'AI is temporarily unavailable right now.',
        chatTitle: 'Ask FinTechTerms',
        chatDescription: 'Ask only finance, fintech, and technology questions.',
        chatPlaceholder: 'Ask about finance, fintech, or technology...',
        chatSend: 'Send',
        chatLoading: 'Thinking with the FinTechTerms glossary...',
        chatReset: 'Clear chat',
        chatGuestLimit: 'Guest preview used. Sign in to unlock the full FinTechTerms chat.',
        chatEmpty: 'Try a glossary question like “What is open banking?”',
    },
    tr: {
        quizFeedbackTitle: 'AI hafıza koçu',
        quizFeedbackLoading: 'Akılda kalıcı açıklama hazırlanıyor...',
        quizFeedbackGuestLimit: 'Guest önizleme hakkı kullanıldı. Tüm AI hata açıklamaları için giriş yap.',
        quizFeedbackContinue: 'Devam et',
        quizFeedbackCta: 'Profili Aç',
        whyWrong: 'Neden kaçtı',
        whyCorrect: 'Ne akılda kalmalı',
        memoryHook: 'Hafıza kancası',
        confusedWith: 'Sık karıştığı kavram',
        explainLabel: 'AI ile açıkla',
        explainLoading: 'AI açıklaması hazırlanıyor...',
        explainGuestLimit: 'Guest önizleme hakkı kullanıldı. Tüm AI açıklamaları için giriş yap.',
        explainModes: {
            simple: 'Daha basit anlat',
            example: 'Örnekle anlat',
            'language-bridge': 'TR / EN / RU köprüsü kur',
            importance: 'Neden önemli',
        },
        studyCoachTitle: 'AI Çalışma Koçu',
        studyCoachDescription: 'Zayıf alanların, favorilerin ve tekrar yüküne göre bugünün planını çıkar.',
        studyCoachGuest: 'AI Çalışma Koçu yalnızca tam üyelere açıktır.',
        studyCoachCompleteProfile: 'AI Çalışma Koçu için profilini tamamla.',
        studyCoachAction: 'Bugünün planını oluştur',
        studyCoachLoading: 'AI çalışma planın hazırlanıyor...',
        studyCoachFocusAreas: 'Odak Alanları',
        studyCoachPlan: 'Bugünün Planı',
        studyCoachReason: 'Bu plan neden önerildi',
        studyCoachNote: 'Koç notu',
        genericError: 'AI şu anda geçici olarak kullanılamıyor.',
        chatTitle: 'FinTechTerms’e Sor',
        chatDescription: 'Sadece finans, fintek ve teknoloji soruları sor.',
        chatPlaceholder: 'Finans, fintek veya teknoloji hakkında sor...',
        chatSend: 'Gönder',
        chatLoading: 'FinTechTerms sözlüğüyle düşünüyor...',
        chatReset: 'Sohbeti sıfırla',
        chatGuestLimit: 'Guest önizleme hakkı kullanıldı. Tam FinTechTerms sohbeti için giriş yap.',
        chatEmpty: '“Open banking nedir?” gibi bir sözlük sorusuyla başlayın.',
    },
    ru: {
        quizFeedbackTitle: 'AI тренер памяти',
        quizFeedbackLoading: 'Готовим запоминающееся объяснение...',
        quizFeedbackGuestLimit: 'Гостевой предпросмотр использован. Войдите, чтобы открыть полный AI-разбор ошибок.',
        quizFeedbackContinue: 'Продолжить',
        quizFeedbackCta: 'Открыть профиль',
        whyWrong: 'Почему это было ошибкой',
        whyCorrect: 'Что нужно запомнить',
        memoryHook: 'Мнемонический якорь',
        confusedWith: 'Часто путают с',
        explainLabel: 'Объяснить с AI',
        explainLoading: 'Готовим AI-объяснение...',
        explainGuestLimit: 'Гостевой предпросмотр использован. Войдите, чтобы открыть полные AI-объяснения.',
        explainModes: {
            simple: 'Объяснить проще',
            example: 'Объяснить на примере',
            'language-bridge': 'Связать TR / EN / RU',
            importance: 'Почему это важно',
        },
        studyCoachTitle: 'AI тренер обучения',
        studyCoachDescription: 'Соберите план на сегодня по слабым местам, избранному и нагрузке повторения.',
        studyCoachGuest: 'AI тренер обучения доступен только полным участникам.',
        studyCoachCompleteProfile: 'Заполните профиль, чтобы открыть AI-тренера обучения.',
        studyCoachAction: 'Построить план на сегодня',
        studyCoachLoading: 'Готовим AI-план обучения...',
        studyCoachFocusAreas: 'Зоны фокуса',
        studyCoachPlan: 'План на сегодня',
        studyCoachReason: 'Почему выбран этот план',
        studyCoachNote: 'Комментарий тренера',
        genericError: 'AI временно недоступен.',
        chatTitle: 'Спросить FinTechTerms',
        chatDescription: 'Задавайте вопросы только по финансам, финтеху и технологиям.',
        chatPlaceholder: 'Спросите о финансах, финтехе или технологиях...',
        chatSend: 'Отправить',
        chatLoading: 'Думаю по словарю FinTechTerms...',
        chatReset: 'Сбросить чат',
        chatGuestLimit: 'Гостевой предпросмотр использован. Войдите, чтобы открыть полный чат FinTechTerms.',
        chatEmpty: 'Начните с вопроса вроде «Что такое open banking?»',
    },
} as const;

export const getAiUiCopy = (language: Language) => aiUiCopy[language];
