-- ==============================================================================
-- CLEAN SYNTHETIC RESEARCH DATA
-- ==============================================================================
-- Use this script to clear all data generated by the python simulation script.
-- CAUTION: This will delete ALL records in 'study_sessions' and 'quiz_attempts'.
-- If you have real user data mixed in, you may want to use a WHERE clause based on criteria.
-- However, since the script generates data with 'simulation' type or specific patterns, we can target that.

-- 1. Clean 'quiz_attempts' table
-- The python script inserts with "quiz_type": "simulation"
-- We can safely delete only these if we want to preserve real user data (if any exists).
-- If you want to wipe everything, remove the WHERE clause.
DELETE FROM public.quiz_attempts 
WHERE quiz_type = 'simulation';

-- 2. Clean 'study_sessions' table
-- The python script generates UUIDs for 'anonymous_id' like 'bot_...'.
-- It also sets 'device_type' and 'user_agent' from Faker.
-- To be safe, checking for IDs starting with 'bot_' is a good heuristic if we want to be surgical.
-- Or if this table is ONLY used for research, TRUNCATE is faster.
DELETE FROM public.study_sessions 
WHERE anonymous_id LIKE 'bot_%';

-- 3. (Optional) Reset Primary Key sequences or Vacuum if needed
-- Not strictly necessary for Supabase/Postgres as UUIDs are used mostly.

-- Verification:
SELECT count(*) as remaining_simulation_attempts FROM public.quiz_attempts WHERE quiz_type = 'simulation';
SELECT count(*) as remaining_bot_sessions FROM public.study_sessions WHERE anonymous_id LIKE 'bot_%';
