-- ⚠ ARCHIVED - DO NOT EXECUTE
-- This file is kept for historical reference only.
-- All study_sessions schema and RLS policies are managed exclusively via:
--   supabase/migrations/20260306170000_phase1_database_unification_lockdown.sql
-- Running any SQL from this file against a live database will revert hardened security policies.
-- Last archived: 2026-03-11
